### ISSUE TITLE
Error while setting up on Arch-based destros.

### ISSUE THREAD

**Issue by swastkk** [Concordium/concordium-node#1010]
**Bug Description**
While I was trying to setup for my Arch Linux, I used `debtap` for converting the `.deb` file to `pkg.tar.zst`  everything went well 
but when I tried to install it with command
```bash
sudo pacman -U concordium-mainnet-node-5.4.2-1-x86_64.pkg.tar.zst
 ````

I am facing this error
```bash

/tmp/alpm_dktS6i/.INSTALL: line 123: warning: here-document at line 15 delimited by end-of-file (wanted `EOF')
/tmp/alpm_dktS6i/.INSTALL: line 124: syntax error: unexpected end of file
/usr/bin/bash: line 1: post_upgrade: command not found
error: command failed to execute correctly
:: Running post-transaction hooks...
(1/2) Reloading system manager configuration...
(2/2) Arming ConditionNeedsUpdate...

```

**Steps to Reproduce**

**Expected Result**
The Node to install 

**Actual Result**
Errors mentioned above!

- OS Arch-Linux
- Browser Brave

**Comment by abizjak** [comment]
The debian package automatically installs a systemd service (actually two of them) and configures them.

I don't have experience with archlinux and debtap so I cannot help with your specific issue, and generally we do not provide support for other distributions.

However the package is relatively simple if you just want to run a node service and you can just extract the relevant binary and systemd configuration files.

Assuming you downloaded the testnet node 6.0.4

1. Extract the archive
```
ar x concordium-testnet-node_6.0.4-0_amd64.deb
```

2. Extract the package data

```
tar xf data.tar.xz
```

3. You will end up with three directories `lib`, `usr` and `var`

```
tree lib usr var 
lib
└── systemd
    └── system
        ├── concordium-testnet-node-collector.service
        └── concordium-testnet-node.service
usr
├── bin
│   ├── concordium-testnet-node-6.0.4
│   └── concordium-testnet-node-collector-6.0.4
└── share
    └── doc
        └── concordium-testnet-node
            └── changelog.gz
var
└── lib
    └── concordium-4221332d34e1694168c2a0c0b3fd0f273809612cb13d000d5c2e00e85f50f796
        ├── config
        └── data
            └── genesis.dat
```

Copy the corresponding files to `/usr`, `/var` or `/lib`.

Finish with `sudo systemctl daemon-reload` to notify systemd about the new service.

And then start it
```
sudo systemctl start concordium-testnet-node
```

**Comment by swastkk** [comment]
Thank you it helped!
