### ISSUE TITLE
Getting Runtime Error!

### ISSUE THREAD

**Issue by swastkk** [Concordium/concordium-node#1015]
How to deal with this error?
Processing line: 2023-08-29T20:17:07.188285565Z: ERROR: A runtime error occurred in the RPC server: transport error

**Comment by abizjak** [comment]
Can you please provide more details as to how you run your node?

This error happens when the server shuts down unexpectedly, for example when it cannot be started properly due to misuse of ports.

**Comment by swastkk** [comment]
> 

I have to change my port in code everytime I want to run the RPC Server. And when server runs it gives me the above error and 2nd time I start the server again, everything works fine.
Wanted to know the reason.

**Comment by abizjak** [comment]
As I wrote above this error occurs when you are trying to start a server on a port where it cannot listen (e.g., because something is already listening there).

There isn't much more I can provide without you providing more details.

**Comment by abizjak** [comment]
Closing due to lack of further details.
