### ISSUE TITLE
Multi-transaction Dry Run

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-node#1016]
This feature adds the ability to dry run a series of transactions to simulate how they would behave if they were run on the chain. The endpoint returns the outcomes of running the transactions.

Feature proposal: https://concordium.atlassian.net/wiki/spaces/EN/pages/1191215111/GRPC+extension+Multi-transaction+Dry+Run

**Comment by mh-concordium** [comment]
What is the release version planned for this epic?

**Comment by abizjak** [comment]
Unclear as of now. 6.1 or 6.2 depending on when it is ready.
