### ISSUE TITLE
Consider storing account maps separately from block state files

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-node#106]
**Task description**

Currently account maps, mapping addresses to account indices, are stored in the block state file directly.

It might be more efficient (space wise, possibly performance-wise) if they were stored separately. 
The following points should be considered
- account maps can in principle always be recovered from the account table.
- accounts are never deleted, so account map is always just extended.

**Sub-tasks**
- [ ] Analyze if this would be the case.
- [ ] Implement if necessary, or close.

**Comment by smh1001** [comment]
Part of database redesign

**Comment by abizjak** [comment]
This is implemented in release 6.2.
