### ISSUE TITLE
Block hash: Merkelize transaction outcomes

### ISSUE THREAD

**Issue by limemloh** [Concordium/concordium-node#1068]
Starting from protocol version 7, the hash of the transaction outcomes should be done as a merkelized binary tree as this will allow for smaller merkle proofs.

**Comment by abizjak** [comment]
Will you close this task since this is already the case since P5?

Or is there more to do here?

**Comment by limemloh** [comment]
Closing this, as mentioned by @abizjak, the transaction outcomes were already merkelized as part of protocol version 5.
Nothing else needs to be done for this task.
