### ISSUE TITLE
Peer nodes and error message the GRPC request failed: Cannot establish connection to GRPC endpoint.

### ISSUE THREAD

**Issue by armanriazi** [Concordium/concordium-node#1074]
**Bug Description**
On the dashboard, I can not see Peers nodes  as well as "Number of packets received/sent" has been shown '0'.
[my test node](https://dashboard.testnet.concordium.com/node/cc5c4234e6478a95)
**Steps to Reproduce**
```concordium-client raw GetNodeInfo```
**Expected Result**
At least 3 peer node. I restarted service node but it did not work
**Actual Result**
`Error: The GRPC request failed: Cannot establish connection to GRPC endpoint.`
**Versions**
- Software Rust 1.72 stable
- OS WSL Ubuntu
- Browser Chrome
- concordium-client 6.1
- concordium-testnet-node(enabled, repeated msg:[INFO  concordium_node::consensus_ffi::ffi]) 6.1.7

**Comment by abizjak** [comment]
Your node is still doing out of band catchup (it's at height 5 million out of 7). Once this is complete it should connect to the rest of the network.

**Comment by abizjak** [comment]
Based on your current progress it looks like a few more hours to fully catch up.
