### ISSUE TITLE
Prototype possible improvements from Wasm interpreter optimizations

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-node#1127]
**Task description**

In order to decide whether we will use Wasmer which brings its own risks, or go towards improving our own interpreter instead, with more limited gains, but likely less work and higher assurance, we want to prototype some improvements quickly and see the gains we can get.

This will feed into the input on whether to use Wasmer or not.

**Comment by syrusakbary** [comment]
Just read this issue after a random search of Wasmer in Github.

It may be useful to know that Wasmer will also add support for a performant interpreter mode soon :)

**Comment by abizjak** [comment]
@syrusakbary Can you shed more light on what "soon" means? Do you have a roadmap? Is there something I can already look at?

This is a time sensitive issue for us.

**Comment by abizjak** [comment]
The prototyping has been done in a low-level-optimizations branch. In the current state it yields 3-4 times real execution time improvement on the most complex transactions we tried.
