### ISSUE TITLE
Smart contract case 1

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-node#1196]
**This task is to be executed after SRE has updated validators to Node 7 but still on Protocol 6**

1. ✅ (used stagenet-99) Use genesis account or create new account using BW, then export keys.
2. ✅ Using grpc node, deploy 5000 modules.
3. ✅ Execute some sc transactions.
   1. ✅ Nodes are not crashing.
   2. ✅ Nodes are keeping up to the final height.
4. ✅ One to three hours before PU start interacting with artifacts again
5. **WAIT FOR PROTOCOL UPDATE**
6. ✅ After the protocol update, verify that the cost is cheaper.

**Comment by limemloh** [comment]
I have prepared a small tool for deploying a lot of modules to stagenet.<br>Let me know when this is needed.
