### ISSUE TITLE
Code clean-up

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-node#124]
**Task description**
Various code clean-up tasks

**Sub-tasks**
- [ ] Reconsider the use of `isFull` in `NominationSet`.
- [ ] Restructure the global state package in line with: [globalstate.txt](https://github.com/Concordium/concordium-node/files/6954478/globalstate.txt)

**Comment by abizjak** [comment]
I am closing this now since the globalstate has gotten a substantial revision since this was created, and it is unclear what the current purpose of this would be.
