### ISSUE TITLE
if the https://hub.docker.com/r/concordium/mainnet-node is under maintenance?

### ISSUE THREAD

**Issue by xinzhongyoumeng** [Concordium/concordium-node#1243]
**Description**
we found the docker repo is not sync with the release. can you give the v7.0.1 docker image? Our node version is 6.3.1-0. and the binary name is concordium-node which is copy from the docker image. Now we found the binary for v7.0.1 
 version is concordium-client_7.0.1-0, but we don't know if is same.
**Steps to Reproduce**

**Expected Result**

**Actual Result**

**Versions**
- Software Version
- OS
- Browser
- Mobile device, if applicable

**Comment by xinzhongyoumeng** [comment]
?

**Comment by limemloh** [comment]
Hi there
Sorry for the late response, 7.0.1 was never available for mainnet as this version was going through testing. This docker image is being maintained and 7.0.5 is now available.

**Comment by xinzhongyoumeng** [comment]
> Hi there Sorry for the late response, 7.0.1 was never available for mainnet as this version was going through testing. This docker image is being maintained and 7.0.5 is now available.

ok, thank you
