### ISSUE TITLE
Reuse transaction database connection pool on protocol update

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-node#145]
**Task description**

Currently, on protocol update, each protocol version will have its own connection pool to the transaction database (if transaction logging is enabled). This does not seem to cause issues, but it would likely be preferable to reuse the connection pool across updates.

**Comment by abizjak** [comment]
This is related to #292 and will be closed by it.

**Comment by EmilLa1** [comment]
Closed due to https://github.com/Concordium/concordium-node/issues/292 being completed some time ago...

**Comment by abizjak** [comment]
For clarity, this has become obsolete since there is no transaction logging in the node anymore.
