### ISSUE TITLE
Block state hash reported as "000...0" for genesis blocks

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-node#147]
**Bug Description**

The reported block state hash for genesis blocks is `"0000000000000000000000000000000000000000000000000000000000000000"`.
Instead, the correct block state hash should be reported.

**Steps to Reproduce**
Call `GetBlockInfo` for the genesis block.

**Expected Result**
The actual hash of the genesis block state.

**Actual Result**
`"0000000000000000000000000000000000000000000000000000000000000000"`.

**Versions**
- Software Version 1.x

**Comment by concordium-cl** [comment]
@abizjak pls put on discourse

**Comment by abizjak** [comment]
Done, remove once this is resolved and the new node is released https://support.concordium.software/t/incorrect-block-state-hash-for-genesis-blocks/148/2
