### ISSUE TITLE
Concordium node has no Avg Ping and Peers

### ISSUE THREAD

**Issue by omkarsunku** [Concordium/concordium-node#161]
Hi Team,

I am running a concordium node from this morning. I am running node on Ubuntu 20.04 LTS with 8GB RAM and 250GB HDD.
As I can see there are no Peers and n/a as Avg Ping time for my node named as "blocktech_dev_om" is there any reason behind this.
Please let me know if any suggestions.

Thanks.
![Screenshot from 2021-09-14 15-01-21](https://user-images.githubusercontent.com/34002297/133233200-1018223c-1bee-493e-a4b5-3a0d0a7e2abb.png)
![Screenshot from 2021-09-14 15-01-21](https://user-images.githubusercontent.com/34002297/133233354-93f5c449-60f0-480c-8b38-691408096546.png)

**Comment by abizjak** [comment]
Are you running the docker distribution? It looks like you are still doing out-of-band catchup. You will not have any peers until that is completed (once your finalized height reaches close to current block height).

This is a question that should be asked on support.concordium.software, so I am closing it here.
