### ISSUE TITLE
Improve transaction logging database resiliency

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-node#191]
_This issue does not require urgent resolution, and may be superseded or become irrelevant in future._

**Description**

Currently, if a reporter node crashes, especially if it corrupts the state database, it may not be possible to restart the node in a way that maintains a coherent transaction database, unless the entire database is wiped and the node restarted from scratch, or the node and database are restarted from a known synchronised state.

In particular, if the node is restarted from scratch, but the transaction database is not wiped, transactions will be duplicated in the database. This might be mitigated by having a unique key on the transaction hash, however, rewards do not have a transaction hash. To overcome this, we might assign a dummy hash to these rewards (that must not clash with a real transaction hash).

Even rolling back the database to a synchronised configuration could potentially lead to issues if wallets expect the ids of transactions to be consistent over time. For instance, the desktop wallet records the maximum id of transactions it has retrieved for an account so that it will not re-download transactions in that range from the wallet proxy. However, if the database is recreated then the ids assigned to transactions could change, resulting in inconsistent handling. We could use a stable property, such as block height, instead. The wallet could ensure that it has all blocks within a range of block heights, and use block height as a cut off in the database query.

**Comment by abizjak** [comment]
This is no longer relevant since the node does not do transaction logging anymore.
