### ISSUE TITLE
Database invariant violation

### ISSUE THREAD

**Issue by crabvk** [Concordium/concordium-node#239]
<details>
  <summary>Full log</summary>
<pre>
<code>
[INFO  concordium_node::utils] Starting up concordium_node version 3.0.1!
[INFO  concordium_node::utils] Application data directory: data
[INFO  concordium_node::utils] Application config directory: config
[INFO  concordium_node::utils] Network: enabled
[INFO  concordium_node::utils] Log level: info
[INFO  concordium_node::p2p::maintenance] My Node ID is ee229cc29effeb53
[INFO  concordium_node::p2p::maintenance] Listening on 142.132.167.17:8888
[INFO  concordium_node] Starting consensus layer
[INFO  concordium_node::plugins::consensus] Starting up the consensus thread
[INFO  concordium_node::consensus_ffi::consensus] Starting up the consensus layer
[INFO  concordium_node::consensus_ffi::ffi] Runner: Starting new chain with genesis block 9dd9ca4d19e9393877d2c44b70f89acbfc0883c2243e5eeaecc0d1cd0503f478 at absolute height 0
[INFO  concordium_node::consensus_ffi::ffi] GlobalState: Using existing PostgreSQL tables for transaction logging.
[INFO  concordium_node::consensus_ffi::ffi] Runner: Starting new chain with genesis block 88846634b2b25f65b723afa856cf38c52655be9fd6bbe1572f1edb529a3a6592 at absolute height 1077518
[INFO  concordium_node::consensus_ffi::ffi] GlobalState: Using existing PostgreSQL tables for transaction logging.
[INFO  concordium_node::consensus_ffi::ffi] Runner: Starting new chain with genesis block 101c9ff77b2dd91fecfc5ff9ad951156c96b1b430d8f5248b08e2db25182ce09 at absolute height 1848787
[ERROR concordium_node::consensus_ffi::ffi] TreeState: Database invariant violation: Block state file exists, but tree state file does not.
[ERROR concordium_node::consensus_ffi::ffi] External: Database invariant violation: Block state file exists, but tree state file does not.
Error: Database invariant violation. See logs for details.
</code>
</pre>
</details>

**Steps to Reproduce**
Kill the node and restart.

**Versions**
- concordium-node 3.0.1
- ArchLinux 5.15.13

**Comment by abizjak** [comment]
It is a known issue that if hte node is killed at the wrong time the database can get corrupted. See #135 for example. We are working on making this more robust.

The failure should not happen if the node is shut down properly, with either sending SIGINT or SIGTERM signals.

The only recovery from such a state is to delete the database. However in your case the failure looks a bit unusual. Did you kill the node just after starting, before first finalization?

**Comment by crabvk** [comment]
No, before killing it was working for about a day.

**Comment by abizjak** [comment]
Did this happen during a protocol update? Why was the node killed?

**Comment by abizjak** [comment]
Seeing that only the last database is corrupted the recommended fix is the following assuming $DATA is the node's data directory
- delete the directory `$DATA/database-v4/treestate-2` (if it exists, which it looks like it does not)
- delete the file `$DATA/database-v4/blockstate-2.dat`

Then your node should catch up since the last update, which was a few hours ago, so catchup will be quick.

**Comment by crabvk** [comment]
Here's the log before killing

<details>
  <summary>Log</summary>
<pre>
<code>
Jan 11 16:56:21 srv-004 concordium-mainnet-node[7923]: [INFO  concordium_node::consensus_ffi::ffi] Skov: Block f0c32dfad77a1d3ac43f15bc39907c41c1714cc1b62b81ba3f9775c283d6f52e (2) arrived
Jan 11 16:56:21 srv-004 concordium-mainnet-node[7923]: [INFO  concordium_node::consensus_ffi::ffi] Skov: Arrive statistics: blocksVerifiedCount=77741 blockLastArrive=1.641920181028909e9 blockArriveLatencyEMA=21505.82191820202 blockArriveLatencyEMSD=128.08
092730718144 blockArrivePeriodEMA=Just 4.032280322828501e-2 blockArrivePeriodEMSD=Just 4.8341400130874394e-2 transactionsPerBlockEMA=0.2518250703813824 transactionsPerBlockEMSD=0.5265044596641645
Jan 11 16:56:21 srv-004 concordium-mainnet-node[7923]: [INFO  concordium_node::consensus_ffi::ffi] Skov: Block f0c32dfad77a1d3ac43f15bc39907c41c1714cc1b62b81ba3f9775c283d6f52e is finalized at height 771268 with finalization delta=0
Jan 11 16:56:21 srv-004 concordium-mainnet-node[7923]: [INFO  concordium_node::consensus_ffi::ffi] Skov: Finalization statistics: finalizationCount=66829 lastFinalizedTime=1.6419201810343244e9 finalizationPeriodEMA=Just 4.369188858905753e-2 finalizationPe
riodEMSD=Just 4.975027278122323e-2
Jan 11 16:56:25 srv-004 concordium-mainnet-node[7923]: [INFO  concordium_node::consensus_ffi::ffi] Runner: Starting new chain with genesis block 101c9ff77b2dd91fecfc5ff9ad951156c96b1b430d8f5248b08e2db25182ce09 at absolute height 1848787
Jan 11 16:56:25 srv-004 concordium-mainnet-node[7923]: [INFO  concordium_node::consensus_ffi::ffi] GlobalState: Using existing PostgreSQL tables for transaction logging.
Jan 11 16:56:38 srv-004 concordium-mainnet-node[7923]: [WARN  concordium_node::p2p::connectivity] Received 4 invalid messages from peer 0000000000000014
Jan 11 16:56:38 srv-004 concordium-mainnet-node[7923]: [WARN  concordium_node::p2p::connectivity] Received 41 invalid messages from peer 0000000000000018
Jan 11 16:56:38 srv-004 concordium-mainnet-node[7923]: [WARN  concordium_node::p2p::connectivity] Received 36 invalid messages from peer 000000000000000d
Jan 11 16:56:38 srv-004 concordium-mainnet-node[7923]: [WARN  concordium_node::p2p::connectivity] Received 74 invalid messages from peer 0000000000000023
Jan 11 16:57:54 srv-004 systemd[1]: concordium-mainnet-node.service: A process of this unit has been killed by the OOM killer.
Jan 11 16:57:54 srv-004 systemd[1]: concordium-mainnet-node.service: Main process exited, code=killed, status=9/KILL
Jan 11 16:57:54 srv-004 systemd[1]: concordium-mainnet-node.service: Failed with result 'oom-kill'.
Jan 11 16:57:54 srv-004 systemd[1]: concordium-mainnet-node.service: Consumed 38min 30.925s CPU time.
Jan 11 16:58:14 srv-004 systemd[1]: concordium-mainnet-node.service: Scheduled restart job, restart counter is at 1.
Jan 11 16:58:14 srv-004 systemd[1]: Stopped Concordium Mainnet Node.
Jan 11 16:58:14 srv-004 systemd[1]: concordium-mainnet-node.service: Consumed 38min 30.925s CPU time.
Jan 11 16:58:14 srv-004 systemd[1]: Started Concordium Mainnet Node.
Jan 11 16:58:14 srv-004 concordium-mainnet-node[8099]: [INFO  concordium_node::utils] Starting up concordium_node version 3.0.1!
Jan 11 16:58:14 srv-004 concordium-mainnet-node[8099]: [INFO  concordium_node::utils] Application data directory: data
Jan 11 16:58:14 srv-004 concordium-mainnet-node[8099]: [INFO  concordium_node::utils] Application config directory: config
Jan 11 16:58:14 srv-004 concordium-mainnet-node[8099]: [INFO  concordium_node::utils] Network: enabled
Jan 11 16:58:14 srv-004 concordium-mainnet-node[8099]: [INFO  concordium_node::utils] Log level: info
Jan 11 16:58:14 srv-004 concordium-mainnet-node[8099]: [INFO  concordium_node::p2p::maintenance] My Node ID is ee229cc29effeb53
Jan 11 16:58:14 srv-004 concordium-mainnet-node[8099]: [INFO  concordium_node::p2p::maintenance] Listening on 142.132.167.17:8888
Jan 11 16:58:14 srv-004 concordium-mainnet-node[8099]: [INFO  concordium_node] Starting consensus layer
Jan 11 16:58:14 srv-004 concordium-mainnet-node[8099]: [INFO  concordium_node::plugins::consensus] Starting up the consensus thread
Jan 11 16:58:14 srv-004 concordium-mainnet-node[8099]: [INFO  concordium_node::consensus_ffi::consensus] Starting up the consensus layer
Jan 11 16:58:15 srv-004 concordium-mainnet-node[8099]: [INFO  concordium_node::consensus_ffi::ffi] Runner: Starting new chain with genesis block 9dd9ca4d19e9393877d2c44b70f89acbfc0883c2243e5eeaecc0d1cd0503f478 at absolute height 0
Jan 11 16:58:15 srv-004 concordium-mainnet-node[8099]: [INFO  concordium_node::consensus_ffi::ffi] GlobalState: Using existing PostgreSQL tables for transaction logging.
Jan 11 16:58:35 srv-004 concordium-mainnet-node[8099]: [INFO  concordium_node::consensus_ffi::ffi] Runner: Starting new chain with genesis block 88846634b2b25f65b723afa856cf38c52655be9fd6bbe1572f1edb529a3a6592 at absolute height 1077518
Jan 11 16:58:35 srv-004 concordium-mainnet-node[8099]: [INFO  concordium_node::consensus_ffi::ffi] GlobalState: Using existing PostgreSQL tables for transaction logging.
Jan 11 17:00:01 srv-004 systemd[1]: Stopping Concordium Mainnet Node...
Jan 11 17:00:01 srv-004 concordium-mainnet-node[8099]: [INFO  concordium_node] Signal received attempting to shutdown node cleanly
Jan 11 17:01:32 srv-004 systemd[1]: concordium-mainnet-node.service: State 'stop-sigterm' timed out. Killing.
Jan 11 17:01:32 srv-004 systemd[1]: concordium-mainnet-node.service: Killing process 8099 (concordium-main) with signal SIGKILL.
Jan 11 17:01:32 srv-004 systemd[1]: concordium-mainnet-node.service: Killing process 8107 (tokio-runtime-w) with signal SIGKILL.
Jan 11 17:01:32 srv-004 systemd[1]: concordium-mainnet-node.service: Killing process 8109 (ghc_ticker) with signal SIGKILL.
Jan 11 17:01:32 srv-004 systemd[1]: concordium-mainnet-node.service: Killing process 8110 (concordium-ma:w) with signal SIGKILL.
Jan 11 17:01:32 srv-004 systemd[1]: concordium-mainnet-node.service: Killing process 8111 (concordium-ma:w) with signal SIGKILL.
Jan 11 17:01:32 srv-004 systemd[1]: concordium-mainnet-node.service: Killing process 8112 (concordium-ma:w) with signal SIGKILL.
Jan 11 17:01:32 srv-004 systemd[1]: concordium-mainnet-node.service: Main process exited, code=killed, status=9/KILL
Jan 11 17:01:32 srv-004 systemd[1]: concordium-mainnet-node.service: Failed with result 'timeout'.
Jan 11 17:01:32 srv-004 systemd[1]: Stopped Concordium Mainnet Node.
Jan 11 17:01:32 srv-004 systemd[1]: concordium-mainnet-node.service: Consumed 2min 58.039s CPU time.
Jan 11 17:01:32 srv-004 systemd[1]: Started Concordium Mainnet Node.
Jan 11 17:01:32 srv-004 concordium-mainnet-node[8140]: [INFO  concordium_node::utils] Starting up concordium_node version 3.0.1!
Jan 11 17:01:32 srv-004 concordium-mainnet-node[8140]: [INFO  concordium_node::utils] Application data directory: data
Jan 11 17:01:32 srv-004 concordium-mainnet-node[8140]: [INFO  concordium_node::utils] Application config directory: config
Jan 11 17:01:32 srv-004 concordium-mainnet-node[8140]: [INFO  concordium_node::utils] Network: enabled
Jan 11 17:01:32 srv-004 concordium-mainnet-node[8140]: [INFO  concordium_node::utils] Log level: info
Jan 11 17:01:32 srv-004 concordium-mainnet-node[8140]: [INFO  concordium_node::p2p::maintenance] My Node ID is ee229cc29effeb53
Jan 11 17:01:32 srv-004 concordium-mainnet-node[8140]: [INFO  concordium_node::p2p::maintenance] Listening on 142.132.167.17:8888
Jan 11 17:01:32 srv-004 concordium-mainnet-node[8140]: [INFO  concordium_node] Starting consensus layer
Jan 11 17:01:32 srv-004 concordium-mainnet-node[8140]: [INFO  concordium_node::plugins::consensus] Starting up the consensus thread
Jan 11 17:01:32 srv-004 concordium-mainnet-node[8140]: [INFO  concordium_node::consensus_ffi::consensus] Starting up the consensus layer
Jan 11 17:01:32 srv-004 concordium-mainnet-node[8140]: [INFO  concordium_node::consensus_ffi::ffi] Runner: Starting new chain with genesis block 9dd9ca4d19e9393877d2c44b70f89acbfc0883c2243e5eeaecc0d1cd0503f478 at absolute height 0
Jan 11 17:01:32 srv-004 concordium-mainnet-node[8140]: [INFO  concordium_node::consensus_ffi::ffi] GlobalState: Using existing PostgreSQL tables for transaction logging.
Jan 11 17:01:50 srv-004 concordium-mainnet-node[8140]: [INFO  concordium_node::consensus_ffi::ffi] Runner: Starting new chain with genesis block 88846634b2b25f65b723afa856cf38c52655be9fd6bbe1572f1edb529a3a6592 at absolute height 1077518
Jan 11 17:01:50 srv-004 concordium-mainnet-node[8140]: [INFO  concordium_node::consensus_ffi::ffi] GlobalState: Using existing PostgreSQL tables for transaction logging.
Jan 11 17:04:43 srv-004 concordium-mainnet-node[8140]: [INFO  concordium_node::consensus_ffi::ffi] Runner: Starting new chain with genesis block 101c9ff77b2dd91fecfc5ff9ad951156c96b1b430d8f5248b08e2db25182ce09 at absolute height 1848787
Jan 11 17:04:43 srv-004 concordium-mainnet-node[8140]: [ERROR concordium_node::consensus_ffi::ffi] TreeState: Database invariant violation: Block state file exists, but tree state file does not.
Jan 11 17:04:43 srv-004 concordium-mainnet-node[8140]: [ERROR concordium_node::consensus_ffi::ffi] External: Database invariant violation: Block state file exists, but tree state file does not.
Jan 11 17:04:43 srv-004 concordium-mainnet-node[8140]: Error: Database invariant violation. See logs for details.
Jan 11 17:04:44 srv-004 systemd[1]: concordium-mainnet-node.service: Main process exited, code=exited, status=1/FAILURE
Jan 11 17:04:44 srv-004 systemd[1]: concordium-mainnet-node.service: Failed with result 'exit-code'.
Jan 11 17:04:44 srv-004 systemd[1]: concordium-mainnet-node.service: Consumed 2min 56.338s CPU time.
Jan 11 17:05:04 srv-004 systemd[1]: concordium-mainnet-node.service: Scheduled restart job, restart counter is at 1.
Jan 11 17:05:04 srv-004 systemd[1]: Stopped Concordium Mainnet Node.
</code>
</pre>
</details>

Looks like the node got out of memory.

**Comment by abizjak** [comment]
Indeed. The node does unfortunately use significantly more memory during a protocol update.

Thank you for this report. Unfortunately you have experienced a known issue which we are trying to address in the upcoming release, at least to some degree.

**Comment by abizjak** [comment]
I am closing this now since in the release that is going to be out today the protocol update should require much less memory overhead. Additionally, the node also has some capacity for database recovery.
