### ISSUE TITLE
Node doesn't appear on the Dashboard consistently

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-node#257]
**Bug Description**
Looking at the logs it seems that protocol update check is performed every time after node gets restarted.

**Steps to Reproduce**
- Install the node and configure it for stagenet.
- Set the DEBUG level of logging.
- Let the node catch up, observe the first lines of logging:
 - Runner: Starting new chain with genesis block 4bfd8e85053b4c11e7e1435f2156248c2affff2a76004da6a65ea702629f09d4 at absolute height 0
 - Runner: Starting new chain with genesis block e8eefd3f22e6d1cb69f0fc9a8acc7fe011ca748d26985529c6b99f14eed96a3d at absolute height 259
-Restart the node. 

**Expected Result**
It is not necessary that this happens every time node gets restarted.

**Actual Result**
Appears to happen after every restart.
[stagenet_old.txt](https://github.com/Concordium/concordium-node/files/8333792/stagenet_old.txt)

**Versions**
- Software Version: Node 4.0.5-delegation-test-5
- OS: macOS Big Sur 11.6.1, Win 11
- MacBook Air (M1, 2020)

**Comment by abizjak** [comment]
@mh-concordium as it is now it is unclear whether anything should be done about it.

Node startup is substantially faster now, and logging is a bit different. Should this remain open, in which case can you please provide some information as to what exactly you think should be done, or close it.

**Comment by mh-concordium** [comment]
Okay, I will look into it once I get to the Mainnet release test (start/stop) this week.

**Comment by mh-concordium** [comment]
This issue was originally about the node doing all the state migrations on startup. It went through all protocol updates every time it was started.
Since this behavior has changed since and it is different today, logging has changed as well. Such logs would appear only during catchup but not every time node is started, therefore, this issue can be closed.
