### ISSUE TITLE
Node doesn't appear on the dashboard consistently after being restarted

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-node#258]
**Bug Description**
It seems that node doesn't consistently appear on the Dashboard after being restarted. This issue was seen on Mac and Windows.

Deleting database files and restarting the node seems to be the workaround. Node appears on the dashboard after database files were deleted and node restarted.

**Steps to Reproduce**

1. Install and configure the node.
2. Set the log level to debug.
3. Node catches up, verify that node is visible on the dashboard.
4. Restart the node.
5. Observe the dashboard and logs.

**Expected Result**
After the node has started it should appear on the Dashboard.

**Actual Result**
Node disappears from the Dashboard. Issue really appears inconsistently, sometimes node appears on the Dashboard after 10-20 mins and sometimes not. However if database files are deleted then it just appears on the Dashboard right after it starts (within minutes).

Logs are flooded with  following line _gRPC failed with “transport error: error trying to connect: tcp connect error: Connection refused (os error 61)” for http://localhost:10002/, sleeping for 5000 ms_ However, when this log is not visible anymore, node seems to be working ok but its still not visible on the Dashboard.

Logs:
[logs.txt](https://github.com/Concordium/concordium-node/files/8333929/logs.txt)

**Versions**
- Software Version: Node 4.0.5-delegation-test-5
- OS: macOS Big Sur 11.6.1, Win 11
- MacBook Air (M1, 2020)

**Comment by abizjak** [comment]
Can you try this out @mh-concordium and confirm it is the same issue?

**Comment by mh-concordium** [comment]
Yes, I will look at it. Thanks.

**Comment by mh-concordium** [comment]
I have added that to configuration (it seems that it works with one "=" sign) and restarted the node. I can see that the node is responsive and it works. Command such as  raw GetNodeInfo returns the info but node doesn't appear on the Dashboard now after 45 minutes.

**Comment by abizjak** [comment]
#244  #245 have now hopefully been addressed, and once we have a stagenet node with that included. We should recheck then, which will most likely be after easter.

**Comment by mh-concordium** [comment]
I wasn't able to reproduce the issue.
Node version:  4.0.9
Client version: 4.0.2

**Comment by abizjak** [comment]
Most likely fixed by #275
