### ISSUE TITLE
Expose foundation account address

### ISSUE THREAD

**Issue by shjortConcordium** [Concordium/concordium-node#259]
**Description**

There is currently no _good_ way to get the current foundation account's address.
It would be nice if there was a way to get it.

Context: The desktop wallet displays the current foundation account, when updating the foundation account, however it does that by extracting the address from a special event in the BlockSummary. Furthermore it seems that this event will be removed in the delegation update.

(The BlockSummary exposes the index of foundation account, but not the address, and it doesn't seem possible to get the address from the index)

**Comment by abizjak** [comment]
`GetAccountInfo` currently allows querying via address or credId. It seems like the best place would be extend this to also support querying by account index. This would be a very small, and fully backwards compatible change.
