### ISSUE TITLE
Node should not issue events for 0 rewards

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-node#260]
**Bug Description**
Node issues events for 0 rewards. This happens for baker or delegator that has to small amount of staked CCDs so it doesn't actually bake a block.

**Steps to Reproduce**

1. Create ID and account with MW.
2. Import backup file with client and add baker. Stake only enough CCDs to go over minimumEquityCapital. 
3. Observe rewards that appear in the transaction details with value 0.
4. It is possible to find out what is the minimumEquityCapital by querrying the node with _client raw GetBlockSummary_

**Expected Result**
If baker/delegator didn't earn anything at the payday, nothing should be shown in the transaction details.

**Actual Result**
<img width="253" alt="Rewards" src="https://user-images.githubusercontent.com/98821384/160114222-a9127eca-671e-460c-a8d8-710da3624681.png">

**Versions**
- Software Version: 4.0.5-delegation-test-5
- OS: n/a
- Browser: n/a
- Mobile device, if applicable: Google Pixel 4a, Android 11

**Comment by td202** [comment]
Fixed in 94e5d4c95fc4822d3ce15f8a6d5c527cb6bedbb5
