### ISSUE TITLE
Node vanished from the dashboard after several days

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-node#274]
**Bug Description**
I was running one passive node on Windows and one baker on Mac. Both nodes just vanished from the dashboard after couple of days. Both nodes were responsive after they vanished, passive one was catching up and I was able to query it. Baker kept getting rewards, seemed like everything else is ok.

Looking a bit more into the Win node, nothing was visible in the Event Viewer, last entry was just regarding starting the node service. node-collector service was also running. I saved logs for Win node. Thinking back, the only thing that possibly happened was that my laptop went to sleep mode and back.

**Steps to Reproduce**
Have a node that is running for a week.

**Expected Result**
Node should be on the dashboard.

**Actual Result**
Node vanished from the dashboard
Restarting the node seems to help, node is back on the dashboard after being restarted.

**Versions**
- Software Version: 4.0.6
- OS: Windows

Log:
[stagenet.log](https://github.com/Concordium/concordium-node/files/8538822/stagenet.log)

**Comment by mh-concordium** [comment]
I wasn't able to reproduce the issue.
Node version:  4.0.9
Client version: 4.0.2

**Comment by abizjak** [comment]
Most likely fixed by #275
