### ISSUE TITLE
Graceful handling of High TPS or high load

### ISSUE THREAD

**Issue by smh1001** [Concordium/concordium-node#330]
When the TPS rate exceeds our current max load (400 TPS), transactions will start to buffer which may worst case lead to Node crashes (OOM).

**Comment by smh1001** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-Blockchain-62566eb023859f00130df2db/issues/Concordium/concordium-node/330?planning-poker) with ZenHub @abizjak @Bargsteen @eb-concordium @EmilLa1 @mkmks @rimbi @td202

**Comment by abizjak** [comment]
Closing for now since we are not working on this. We'll recreate when we resume work on it.
