### ISSUE TITLE
Improve transaction verification types.

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-node#346]
Today the following types in `Concordium.TransactionVerification` is a bit convoluted. 
The code could be cleaner - and we will even be able to get rid of a few unnecessary `map` invocations.

In particular:

`doReceiveTransactionInternal :: (TreeStateMonad m) => TV.TransactionOrigin m -> BlockItem -> Timestamp -> Slot -> m (Maybe (BlockItem, Maybe TV.VerificationResult), UpdateResult)`

should become: 

`doReceiveTransactionInternal :: (TreeStateMonad m) => TV.TransactionOrigin m -> BlockItem -> Timestamp -> Slot -> m (Maybe TV.BlockItemWithStatus, UpdateResult)`

Consequently 
`addBlock :: forall m. (HasCallStack, TreeStateMonad m, SkovMonad m, FinalizationMonad m, OnSkov m) => PendingBlock -> [Maybe TV.VerificationResult] -> m UpdateResult`

should be 
`addBlock :: forall m. (HasCallStack, TreeStateMonad m, SkovMonad m, FinalizationMonad m, OnSkov m) => PendingBlock -> [TV.VerificationResult] -> m UpdateResult`

and subsequently when executing pending blocks it should be asserted that there are no finalized transactions returned (i.e. `Nothing` for the `getNonFinalizedTransactionVerificationResult` call. 
If that is the case then the block should be rejected. 

Additional types that should be considered:

`BlockItemWithStatus`
`TransactionWithStatus`
`CredentialDeploymentWithStatus`
`ChainUpdateWithStatus`

These types should not hold a `Maybe VerificationResult` but instead it should be `VerificationResult`.

**Comment by EmilLa1** [comment]
@abizjak Can I close this, as it is not relevant for the new consensus protocol ?

**Comment by abizjak** [comment]
ok.
