### ISSUE TITLE
Document out-of-band catch-up on Ubuntu

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-node#367]
**Task description**

Document how to synchronize with the network quickly via out-of-band catch-up on Ubuntu nodes.
We already have similar documentation for [macOS](https://developer.concordium.software/en/mainnet/net/guides/run-node-macos.html#synchronize-a-node-with-the-network) and [Windows](https://developer.concordium.software/en/mainnet/net/guides/run-node-windows.html#synchronize-a-node-with-the-network).

The process is a bit more involved on Ubuntu (than on macOS and Windows) due to the sandboxing, so you cannot just put the file anywhere you want. 
We already have documentation for how to [add baker credentials to an Ubuntu node](https://developer.concordium.software/en/mainnet/net/nodes/baker-ubuntu.html#baker-ubuntu), which faces the sandboxing issues, so read that guide for inspiration.

**Comment by abizjak** [comment]
Note that this was documented by linking to the (section of the) README in the node repository.

I have added the relevant parts of the readme to the documentation now.

**Comment by abizjak** [comment]
Closed by https://github.com/Concordium/concordium.github.io/pull/539
