### ISSUE TITLE
Overflow when computing rewards

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-node#373]
**Bug Description**

In computing delegation rewards in P4, there are a number of places where integer overflow can occur, resulting in incorrect calculation of reward amounts. This comes about because `Ratio a` (where `a` is representationally `Word64`) is used in calculations of the form `(a / b * c)`, and if `a * c` exceeds the max bound for `Word64`, an overflow occurs resulting in the calculated value being smaller than the correct value.

The following calculations are affected:

- finalization, baking and transaction rewards to delegators (`rewardDelegators`)
- pool baking rewards (`rewardBakers.rewardBaker`)
- pool finalization rewards (`rewardBakers.rewardBaker`)

Note that there are some cases where this issue is avoided by converting the `Ratio` to a `Rational` before doing the calculation, which negates the possibility of an overflow. In particular, the computation of the fraction of finalization rewards to passive delegators and the fraction of baking rewards to passive delegators should be correctly calculated.

**Steps to Reproduce**

For the rewards to delegators, contrive a scenario in which:
- An account delegates `d` to a pool with total capital `p`.
- `d` and `p` do not have a common factor
- The reward to the pool of a certain type (finalization, baking or transaction fee) after the baker's commission is taken is `r`
- `r * d` (in microCCD^2) exceeds 2*10^19.

**Expected Result**

The reward values are as expected.

**Actual Result**

The reward values are (substantially) lower than the expected values.

**Versions**
- Software Version 4.0.11

**Comment by abizjak** [comment]
Closed by #387
