### ISSUE TITLE
Incorrect block reward calculation

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-node#376]
**Bug Description**

In the block reward calculation for P4, the `poolFees` (i.e. the share of the transaction fees that accrue to the block's baker pool) was defined to be `poolsAndPassiveFees - passiveOut`.
It should have been defined as `poolsAndPassiveFees - passiveTransFees`.

This can lead to CCDs disappearing. (Or potentially, in the case of an underflow, appearing.)

**Steps to Reproduce**

Have an account with a significant passive delegation.
Ensure that sufficient transactions are carried out that rewards are paid to passive delegation.
On a block with transactions, compute the sum of the following:
- the balance of the GAS account (`concordium-client raw GetRewardStatus` to see)
- the amount rewarded to the baker pool
- the amount rewarded to passive delegation
- the amount rewarded to the foundation (see node dashboard or `concordium-client raw GetBlockSummary` for these three).
The result should match the sum of:
- the total transaction fees paid on the block
- the balance of the GAS account on the previous block

**Expected Result**
The values match.

**Actual Result**
The values do not match.

**Versions**
- Software Version 4.0.11

**Comment by abizjak** [comment]
Closed by #387
