### ISSUE TITLE
Remove or reduce the delegators stake while delegator is violating leverage bound

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-node#386]
**Bug Description**
In scenario where delegators stake is equal to the pool limit and delegator has restaking enabled, pool limit will be breached after delegator received rewards. This is not an issue and it was decided that it is the way Delegation should work. However, once delegator is in violation the leverage bound, delegator can't remove nor reduce the stake.
 
**Steps to Reproduce**
Open a pool with 100M stake.
Delegate 200M to that pool, select rewards to restake.
When delegator has more than 200M try to:
- Stop/Remove Delegator
- Reduce the stake so that it would not violate leverage bound anymore.

**Expected Result**
User should be able to reduce the stake or remove delegator.

**Actual Result**
User can't reduce the stake nor remove delegator. Transaction gets rejected with `Warning: Baking pool's total capital would become too large.` 

**Versions**
- Software Version: 4.1.0

**Comment by abizjak** [comment]
Closed by #387
