### ISSUE TITLE
Defense against malicious or "dead" blocks and messages.

### ISSUE THREAD

**Issue by smh1001** [Concordium/concordium-node#406]
There are currently a few scenarios where the node will accept and (temporarily) store, and retransmit blocks and finalization messages that are invalid. This can be used to slow down or stop the network with "no" cost (other than some network traffic and CPU cost for the attacker).
In the worst case it can be used to stop finalization, or to cause unbounded increase in memory consumption of all the nodes on the network, leading to them being killed.

- Validate pending blocks as much as possible, in particular in most cases we can validate whether the claimed baker had the right to bake the block.
- Finalization messages for the finalization index after the current one are unvalidated, stored, and retransmitted. Catchup is also triggered (as in the previous item). Investigate what we can do here.
- There is no limiting of catchup requests. This can be used for a targetted attack. We can introduce rate-limiting per peer.

**Comment by smh1001** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-Blockchain-62566eb023859f00130df2db/issues/Concordium/concordium-node/406?planning-poker) with ZenHub @abizjak @Bargsteen @EmilLa1 @mkmks @td202

**Comment by abizjak** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-Blockchain-62566eb023859f00130df2db/issues/Concordium/concordium-node/406?planning-poker) with ZenHub @rimbi
