### ISSUE TITLE
Auto-test: TPS test

### ISSUE THREAD

**Issue by smh1001** [Concordium/concordium-node#414]
The test team should have ownership over the specification and process of the TPS tests. For setup and execution, close cooperation with devops is to be specified.

On Core Blockchain team to specify the TPS tests. Regression testing to make sure that performance is not going backward between releases.

Epic is partly shared with DevOps.

* define metrics (numbers, setup, ...) and align with stakeholders
* process for execution (how often, who does what)
* report test results in a structured way

**Comment by smh1001** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-Blockchain-62566eb023859f00130df2db/issues/Concordium/concordium-node/414?planning-poker) with ZenHub @abizjak @Bargsteen @EmilLa1 @mkmks @rimbi @smh1001 @td202

**Comment by mh-concordium** [comment]
@abizjak 
If you agree, I would close this issue since we have established the process, we have agreed on metrics we are collecting  and we agreed that we will do TPS tests when needed based on our assessment.

**Comment by abizjak** [comment]
I agree to consider this done.

**Comment by mh-concordium** [comment]
Great! Closing it down.
