### ISSUE TITLE
Node caching - LRU revisited

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-node#419]
The lru cache which was used for initial micro benchmarks https://github.com/Concordium/concordium-node/pull/370 is not optimal, there are more reasons as to this but overall the dependency does not seem to be implemented with efficiency as a very high priority, in particular it uses the lazy Data.Map internally. 

We should be able to produce a solution that fits better into our use case and thus we must implement our own LRU cache. 

For instance we can make use of the efficient `IntMap` for internal book keeping as we are storing `BlobRef´ which is just a Word64. 

After implementation we should also integrate this into our benchmark setup for the caches.

**Comment by rimbi** [comment]
The custom implementation I worked on performed way worse than the existing LRU and FIFO cache solutions. The solution was based on lists. I also tried a solution using a priority search queues. It did not help much either. They were roughly 50x~100x slower than the current solutions.

I am stopping working on this solution as there are other tasks with higher priorities.
