### ISSUE TITLE
Update the developer documentation removing references to the "concordium-software" package and providing migration instructions.

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-node#428]
This is related to #427 .

It covers updating the developer documentation to remove downloads of the concordium-software distribution, as well as migration instructions for users of that distribution.

**Comment by mh-concordium** [comment]
Tested Testnet node 4.2.1-2 - used config from the guide, run node with docker compose, node is catching up.
Tested Mainnet node 4.2.1-2 - used config from the guide, run node with docker compose, node is catching up.
