### ISSUE TITLE
Cache persistent account data

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-node#436]
The initial version of account caching caches the entirety of each account as a unit. It would likely be more efficient to always retain the volatile parts of the account (i.e. nonce, balance and account hash) but cache the remaining parts (persistent account state, encrypted balance, release schedule and staking). (In any case, we already retain the hash, so retaining the nonce and balance only adds 16 bytes extra overhead per account, in theory.)

**Comment by rimbi** [comment]
Postponed
