### ISSUE TITLE
Average throughput is not maintained correctly

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-node#46]
**Bug Description**
The send/receive throughput reported via the GRPC APIs seem to be inaccurate, and generally report 1bps sent/received.

**Steps to Reproduce**
Run a node. Observe the average sent/received values in the node dashboard.

(Note, as far as I can tell, these stats are not currently available through a query from `concordium-client` query.)

**Expected Result**
Reasonable values > 0.001 kB/s.

**Actual Result**
0.001 kB/s.

**Versions**
- Software Version: 0.7.2
- OS: Windows

**Comment by abizjak** [comment]
Fixed by #56
