### ISSUE TITLE
Contract state lookup optimization

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-node#497]
Contract state is always looked up on disk however it still seems to be CPU bound from benchmarks.
Hence there is room for optimization to make lookups faster.

The bottleneck(s) must be identified and addressed.  

Benchmarks from before and after should be obtained.

**Comment by abizjak** [comment]
It seems to me that this is for now adequately addressed #504 seeing that there is little difference from before caching.

**Comment by EmilLa1** [comment]
I agree. Closing this for now.
