### ISSUE TITLE
Relax smart contract resource restrictions

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-node#530]
**Task description**

There are some resource restrictions related to smart contracts that are probably not necessary. We have decided to relax some of the most troublesome ones. These are
- parameter size (1kB at the moment)
- return value size (16kB at the moment)
- 64 log items per section, 512B per log item
- Only charge the first time a module is used in a transaction (this changes cost accounting, and will likely improve memory footprint)

If we have time we should analyze the transient memory used, but it is not a priority.
- (Tentative) 32MB transient memory available to contracts (analyze first)

**Comment by Bargsteen** [comment]
Closed with #563
