### ISSUE TITLE
Document the new GRPC API in the developer documentation.

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-node#552]
Explain that we have the new API, how it is enabled in distributions, and link to the proto files and more detailed configuration options.

**Comment by mh-concordium** [comment]
Add to documentation part related to upgrading nodes. Users that currently have nodes will have to merge configuration files.
Configuration files appear differently depending on distribution. For example, on Mac, configuration file is not overwritten after updating the node while on Windows is.
