### ISSUE TITLE
Node version in Windows Installer was not changed to 5.1.0

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-node#624]
**Bug Description**
Installing 5.1.0 version seems as 5.0.6 was installed. The actual node installed was really 5.1.0 but 

**Steps to Reproduce**
Install the Node 5.1.0 on Windows.

**Expected Result**
- Looking at the Node through Control Panel -> Apps - version should be 5.1.0
- Default path in the installation wizard should be pointing to 5.1.0 (C:\Program Files\Concordium\Node 5.1.0\)

**Actual Result**
- Looking at the Node through Control Panel -> Apps - version is 5.0.6
- Default path in the installation wizard is pointing to 5.0.6 (C:\Program Files\Concordium\Node 5.0.6\)

**Versions**
- Software Version: 5.1.0
- OS: Windows

**Comment by abizjak** [comment]
We'll change it for the next stagenet deploy if that's OK. And not for 5.1.0.

**Comment by abizjak** [comment]
This was fixed for the 5.1.1 version as per the comment above. So closing.
