### ISSUE TITLE
Remove basic block state usage in Consensus tests

### ISSUE THREAD

**Issue by limemloh** [Concordium/concordium-node#667]
A few of the unit tests related to consensus (the current consensus) uses basic block state and should be rewritten to use the persistent block state implementation.

The relevant unit test files in `concordium-consensus/tests/consensus/` are: 
- [x] `ReceiveTransactionsTest.hs`
- [ ] `Konsensus.hs`
- [x] `PassiveFinalization.hs`
- [x] `FinalizationRecover.hs`
- [ ] `CatchUp.hs`

**Comment by limemloh** [comment]
The remaining work on removing basic block state from `Konsensus.hs` more time than expected and is therefore put on hold for now, in order to prioritize the actual simplification.
We should get back to this afterwards.

**Comment by limemloh** [comment]
The remaining work on removing basic block state from `Konsensus.hs` more time than expected and is therefore put on hold for now, in order to prioritize the actual simplification.
We should get back to this afterwards.

**Comment by limemloh** [comment]
Since we are working on a new consensus and not including any new features to the current consensus at the moment, this task will be postponed indefinitely. It should be implemented if a bug is discovered in the current consensus.

**Comment by abizjak** [comment]
I believe we agreed to remove the tests that are currently commented out. Can we do that instead of leaving them commented out?

**Comment by abizjak** [comment]
Closing this since the remaining tests have been removed.
