### ISSUE TITLE
Node version in the Windows Installer is old

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-node#706]
**Bug Description**
Version in the Windows installer for the Node 5.2.0 is still 5.1.3, we should remember fix this with the next internal release to Stagenet.

**Steps to Reproduce**
Install the node 5.2.0 on Windows.

**Expected Result**
Version that is in the installation path and in the list of applications (Settings>Apps) should be 5.2.0.

**Actual Result**
Version that is in the installation path and in the list of applications (Settings>Apps) is still 5.1.3.

**Versions**
- Software Version: 5.2.0
- OS: Windows

**Comment by abizjak** [comment]
Good catch. Let's fix this in the next version.
