### ISSUE TITLE
New Consensus: Consolidate logging

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-node#792]
Figure out what is appropriate for logging and at what level it should be in the new consensus protocol.

In particular the following modules should be checked whether the logging is appropriate. 

- [x] Timeout module (added WARN logging to flaggable offences)
- [x] Quorum module (added WARN logging to flaggable offences)
- [x] Blocks module (Changed all log stmts for flaggable offences to be at WARN level.)

**Comment by abizjak** [comment]
@EmilLa1 All the tasks in this issue have been checked off. Is this to be closed?

**Comment by EmilLa1** [comment]
> @EmilLa1 All the tasks in this issue have been checked off. Is this to be closed?

The checkboxes refer to the progress of the corresponding PR https://github.com/Concordium/concordium-node/pull/866

This is not merged, so in that regard we can't close this issue. 

However, as stated in the PR. It's not clear if we actually want to do anything about it right now - perhaps it should be done at a later stage when we will actually make use the flagging mechanism. 
So in that regard, I think we should close this issue and the PR now. @abizjak Agree?
