### ISSUE TITLE
Fix or remove the use of the envoy proxy

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-node#81]
**Task description**

In the distribution docker image we use the envoy proxy to proxy GRPC requests from the node dashboard. The way this is built is not properly versioned. It uses getenvoy which is installed from an unversioned source, which then leads to frequent breakage. It also looks like versions are frequently deprecated.

In order for the build not to break all the time we need to fix the versions in some way so that things don't break every 2 months.

Ideally we'd use just the nginx, but that does not support proxying grpc over http/1, and browsers do not support http/2 over unencrypted connections. And we shouldn't complicate things with https on localhost.

**Comment by concordium-cl** [comment]
Irrelevant as we move to electron.
