### ISSUE TITLE
Node doesn't start on Mac

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-node#820]
Try to install and start the node for Testnet results with error:
`launchctl error 6
6: Device not configured`

Staring it from the launchpad:
![image.png](https://images.zenhubusercontent.com/6284893f971a3daf4db6e569/855a6f3d-e81d-42c1-af9a-6f88dc575165)

**Version:** 5.3.2

**Comment by mh-concordium** [comment]
Seems to be working fine now with 5.3.2-1. I was able to install it and it is catching up on Testnet.

**Comment by Bargsteen** [comment]
Great 😊
