### ISSUE TITLE
There seems to be an issue with creating the state at genesis from the genesis data

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-node#859]
**Bug Description**
In the genesis data generated with creator, bakers defined in `accounts.json`  have restaking flag set to false `"restakeEarnings": false,` but when the chain starts, bakers are restaking.

**Steps to Reproduce**

1. Generate genesis data with genesis-creator version 0.2.0.
2. Start the local chain.
3. Look at the  baker account on chain and compare it to the definition in `accounts.json`.

**Expected Result**
All the bakers should not restake rewards.

**Actual Result**
All the bakers are staking the rewards.

**Versions**
- Software Version: 6.x

**Comment by td202** [comment]
This bug affects version 5.x, and only when the genesis data is for protocol version P5 (or later).
