### ISSUE TITLE
All CCDs are staked in the first payday after starting from genesis

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-node#863]
**Bug Description**
Right after I start the chain from genesis, it seems that all the CCDs are staked. So basically, `totalAmount = totalStakedCapital`  but only before the `nextPayday `actually happens. Then `totalStakedCapital ` gets down to the correct number.

**Steps to Reproduce**
1. Start the local chain from genesis
2. `GetRewardStatus ` right after starting the chain:
```
 {
    "bakingRewardAccount": "0",
    "finalizationRewardAccount": "0",
    "foundationTransactionRewards": "0",
    "gasAccount": "0",
    "nextPaydayMintRate": 2.61157877e-8,
    "nextPaydayTime": "2023-05-26T12:50:00Z",
    "protocolVersion": 6,
    "totalAmount": "9000000000000000",
    "totalEncryptedAmount": "0",
    "totalStakedCapital": "9000000000000000"
} 
```
3. GetRewardStatus after `"nextPaydayTime": "2023-05-26T12:50:00Z"`

```
{
    "bakingRewardAccount": "2",
    "finalizationRewardAccount": "0",
    "foundationTransactionRewards": "0",
    "gasAccount": "0",
    "nextPaydayMintRate": 2.61157877e-8,
    "nextPaydayTime": "2023-05-26T12:58:00Z",
    "protocolVersion": 6,
    "totalAmount": "9000000235042089",
    "totalEncryptedAmount": "0",
    "totalStakedCapital": "2000000000000000"
}
```

**Expected Result**
I would assume that only CCDs that were defined in genesis as staked would appear to be staked on chain.

**Actual Result**
`totalAmount = totalStakedCapital` is true until first payday after starting the chain happens.

**Versions**
- Software Version: 6.0

**Comment by mh-concordium** [comment]
This was not an issue in node 5.3.2. I have tried to run a local chain with that node and the total staked amount is correct right after starting a chain.

**Comment by abizjak** [comment]
What protocol version do you start on?

**Comment by mh-concordium** [comment]
> This was not an issue in node 5.3.2. I have tried to run a local chain with that node and the total staked amount is correct right after starting a chain.

I have made a mistake because I was running a node with the genesis time that has already passed, therefore I was not able to see this issue in 5.3.2.

However, inspecting genesis block indeed shows that this is an old issue.
