### ISSUE TITLE
Scheduled releases

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-node#900]
**Task description**
- Run **Scheduled releases** in a wallet. See tab _Delegator/Account - start BEFORE pu_ in [protocol update test (internal document)](https://docs.google.com/spreadsheets/d/133ntcl7cavbn8jv3XAg43hFzehrC6YE0LCjnN5tEv6g/edit?usp=sharing) for steps.
- Use CCDScan and wallet for monitoring.

**Comment by mh-concordium** [comment]
Case 1:
Release  2777.777833 CCD every hour.
Release starts `Wed, 21 Jun 2023 13:00:00 UTC: 2777.777777 CCD`
Release ends `Sat, 24 Jun 2023 12:00:00 UTC: 2777.777833 CCD`

Transaction hash on Stagenet: `82f8bda7d28c789f550937afa66d4642f81e4070062ed7d8706d825ddfb81a73`
Block where tx was finalized: `791218ed49a7742399308bb8b860535569ece615512d20c44f842c1f96c19be8`

Case2:
Release 40 CCD every hour
Release starts `Fri, 23 Jun 2023 06:00:00 UTC: 40.000000 CCD`
Release ends `Fri, 23 Jun 2023 10:00:00 UTC: 40.000000 CCD`

Transaction hash on Stagenet: `a838d17c19ed84dec395ecc48072227fa2b2ac927f269f7fef629ec125996cb3`
Block where tx was finalized: `10a6e66db0134d33bec2d6be7938e6fbc9f6b4bc79bbfaa8204b94d789ec246f`

**Comment by mh-concordium** [comment]
Scheduled releases that were initiated before PU continued to be released after PU.
