### ISSUE TITLE
Mismatch between Delegator Payout and Commissions

### ISSUE THREAD

**Issue by tschudid** [Concordium/concordium-node#931]
**Bug Description**

In some cases the payout to pool delegators does not match the expected payout according to the set pool commissions.

Example on current stagenet:

Payout block `5bc6826e622f22155dbf6c097d38022689fc2676184354e13790ead19db9d77c`

Pool `0` has baking commission set to `100%` 
(via `concordium-client .. raw GetPoolStatus --pool 0 5bc6826e622f22155dbf6c097d38022689fc2676184354e13790ead19db9d77c`)

Account `44q8cx7CBe9qwhvbNs19YB2Q8RHqtR24SkpK44epSLXM1EFqhF` delegates to pool `0`
(via `concordium-client .. raw GetAccountInfo 44q8cx7CBe9qwhvbNs19YB2Q8RHqtR24SkpK44epSLXM1EFqhF 5bc6826e622f22155dbf6c097d38022689fc2676184354e13790ead19db9d77c`)

Account `44q8cx7CBe9qwhvbNs19YB2Q8RHqtR24SkpK44epSLXM1EFqhF` gets `216` microCCD baking rewards
(via `concordium-client .. raw GetBlockSpecialEvents 5bc6826e622f22155dbf6c097d38022689fc2676184354e13790ead19db9d77c`)

**Steps to Reproduce**

Unclear. In the above example, the baking commission was set to `100%` at the start of the payday.

**Expected Result**

The account `44q8cx7CBe9qwhvbNs19YB2Q8RHqtR24SkpK44epSLXM1EFqhF` should get `0` baking rewards.

**Actual Result**

The account `44q8cx7CBe9qwhvbNs19YB2Q8RHqtR24SkpK44epSLXM1EFqhF` got `216` baking rewards.

**Comment by abizjak** [comment]
For posterity, this is node version 6.0.0, at protocol version 6.

**Comment by abizjak** [comment]
I think the commission rates for that baker have changed during the previous payday.

```
concordium-client raw GetPoolStatus --pool 0 eb2f328dcf2ddf51f4998cc4d17ed0f1fe671fc0ccc115375e6f3a6934dc0dee                                                                
{
    "allPoolTotalCapital": "17239881609563268",
    "bakerAddress": "4fvxZZ225xcEiCkgXTZt3cSReYgbxiMsSoj1UhAbGCsqvVg9N7",
    "bakerEquityCapital": "3000000000000000",
    "bakerId": 0,
    "bakerStakePendingChange": {
        "pendingChangeType": "NoChange"
    },
    "currentPaydayStatus": {
        "bakerEquityCapital": "3000000000000000",
        "blocksBaked": 0,
        "delegatedCapital": "2065860373294",
        "effectiveStake": "3002065860373294",
        "finalizationLive": true,
        "lotteryPower": 0.17425627737918772,
        "transactionFeesEarned": "0"
    },
    "delegatedCapital": "2065860373815",
    "delegatedCapitalCap": "6000000000000000",
    "poolInfo": {
        "commissionRates": {
            "bakingCommission": 0.15,
            "finalizationCommission": 0.9,
            "transactionCommission": 0.12
        },
        "metadataUrl": "",
        "openStatus": "openForAll"
    },
    "poolType": "BakerPool"
}
```

And the commission rates effective during the reward period are used for bakers if I recall correctly.

**Comment by abizjak** [comment]
Do you agree with that @tschudid ?

**Comment by tschudid** [comment]
Yes, the commission rates changed at the beginning of the reward period (around block `a82263e3dfe08e911413c46646b3d2e64d93a3992754ff817b1e54d569e86b74`).
If the old commission rates are used, the delegator should indeed get baking rewards (as observed).

**Comment by tschudid** [comment]
If this is the intended behaviour, the information from gRPC's `GetPoolInfo` is confusing. 
The returned `PoolInfoResponse` contains `information about a given pool at the end of a given block.`
So I would assume that it shows the relevant commission range (which would be the "old" one) during the whole reward period. But this is not the case.
