### ISSUE TITLE
Finalizer that is not in the committee receives reward for 1 payday

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-node#937]
**Bug Description**
One of the finalizers gets replaced in the finalization committee because other baker joins to committee with higher stake. After the change is in effect, old finalizer receives finalization reward for one payday.  So to sum up, there is one payday where there were 4 finalizer rewards distributed while minimumFinalizers=3, maximumFinalizers=3.

**Steps to Reproduce**
1. Setup chain parameters in genesis `minimumFinalizers=3, maximumFinalizers=3, finalizersRelativeStakeThreshold=0.001, capitalBound=1`
2. Start a chain with 3 finalizers, each has 100M stake.
3. After several paydays, add another baker that has 150M stake.
5. Observe rewards distribution for the first and second payday after you have added new baker.

**Expected Result**
There would always be 3 finalization rewards since committee is limited to 3 finalizers.

**Actual Result**
In the payday after committee change is in effect, there are 4 finalization rewards for 4 pools.
Looking at the logs, QC was always signed only by 3 indices 0, 1, or 2.

**Versions**
- Software Version: 6.
- Protocol version:6.

This issue could be related to https://github.com/Concordium/concordium-node/issues/931

**Comment by abizjak** [comment]
So looking at the description here, I think this is a consequence of the fact that the first blocks in an epoch will have QCs signed by the finalizers for the previous epoch. So in the first payday after a finalizer is removed from the committee it will still have a QC with its signature on it, and thus count as a "live" finalizer for that payday.

I think this is reasonable behaviour, even if perhaps a bit surprising. It is a bit inconsistent with the behaviour if a finalizer is removed (as in deregistered) though.

Can you pitch in on this @chportma @chrmatt @td202 @EmilLa1 @eb-concordium ?

**Comment by chportma** [comment]
Aleš is right. A block contains a QC for the parent. So the first block in an epoch will have the QC for the last block of the previous epoch which has the signatures of the finalization committee of the previous epoch.

The correct behavior for distributing rewards would be that having a signature appearing in a block B means that this finalizer should get rewards for the payday of the parent of B. But if this is too inconvenient to implement, we could settle for an intermediary solution, where we don't count the signatures in the first block of an epoch when determining which finalizer was live for a payday.

**Comment by chportma** [comment]
Sorry, accidentally clicked on close.

**Comment by abizjak** [comment]
I would go with the existing behaviour, which is option 1 I suppose.

My rationale being that this will only happen when a finalizer is kicked out of the committee by another finalizer, and then the downside is they get a reward for one extra payday (at least if they are alive at the right time). So it seems the  downside of this is pretty limited.

I think I prefer that to option 2.

I think option 3 is too complex with the way things are implemented, and I don't think it makes sense to add complexity for this corner case.

**Comment by abizjak** [comment]
Based on the discussion above, and in slack with @chrmatt and @tschudid we will keep the behaviour as is due to the reasons listed in the messages above.

We'll try to find a place to document this edge case.
