### ISSUE TITLE
Tokenomics tests

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-node#943]
[placeholder]

**Comment by concordium-cl** [comment]
Hey @tschudid I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/core-blockchain-62566eb023859f00130df2db/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account.
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by mh-concordium** [comment]
Completed. [Internal notes](https://docs.google.com/spreadsheets/d/1quRwgktmQfHqW_sV217QoULhz47ntH0W9GvQAGvMOik/edit#gid=0).
