### ISSUE TITLE
Test of new smart contract functionality - Rollback

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-node#944]
- Tests should be executed on stagenet with node version 6.0.1 and protocol version 6.
- Tests should be completed between 05-07 (when stagenet is expected to be ready in the newest versions) and 31-07 (when stagenet is reset).
- As usual, please get all the details from @abizjak.

**Comment by concordium-cl** [comment]
Hey @chrmatt I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/core-blockchain-62566eb023859f00130df2db/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account.
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by chrmatt** [comment]
## Overview
To perform the testing reasonably efficiently, a single smart contract that takes a parameter and based on the parameter either calls itself or another instance of the same contract possibly multiple times and fails or succeeds. The smart contract has a counter in its state that is incremented in each invocation, and 10 CCD are always transferred to another account. The contract also contains a function to compute the expected outcome if there are no issues. Some tests have also been performed on Testnet to ensure that something relevant is tested.

The code of the contract is [attached](https://app.zenhub.com/files/352905367/1a18a1f4-64bc-405e-986a-7a137b396d65/download).

## Tests and Results

### Warmup, Test case 0:
call A:
- increment
- transfer CCD
- call A again causing infinite recursion

**expected outcome:**
- run out of gas
- counter and account balance of other are unchanged

**result:**
- as expected

### Test case 1:
```
A
	B
		A
		fail
	succeed
succeed
```
parameter: 008_006

**expected outcome:**
- A counter: +1
- B counter: +1
- other balance: +20

**result:** as expected
**Testnet:** same (!)

### Test case 2:
```
A
	B
		A
			A
				A
				succeed
			fail
		succeed
	succeed
succeed
```
parameter: 002_004_006_006

**expected outcome:**
- A counter: +2
- B counter: +1
- other balance: +30

**result:** as expected
**Testnet:** same

### Test case 3:
```
A
	B
		A
		succeed
		A
		fail
		A
		succeed
	succeed
succeed
```
parameter: 686_006

**expected outcome:**
- A counter: +3
- B counter: +1
- other balance: +40

**result:** as expected
**Testnet:** same

### Test case 4:
```
A
	B
		A
		fail
	fail
	B
		A
		fail
	succeed
	B
		A
		fail
	fail
succeed
```
parameter: 008_868

**expected outcome:**
- A counter: +1
- B counter: +1
- other balance: +20

**result:** as expected
**Testnet:** B counter +2

### Test case 5:
```
A
	B
		A
		succeed
	fail
	B
		A
		succeed
	succeed
	B
		A
		succeed
	fail
succeed
```
parameter: 006_868

**expected outcome:**
- A counter: +2
- B counter: +1
- other balance: +30

**result:** as expected
**Testnet:** B counter +2

### Other "random" parameters tried (all ok):
- 888242666868866
- 422444222682246
- 423567232187122
- 468862263888666
