### ISSUE TITLE
Test of new smart contract functionality - Sponsored transactions

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-node#945]
- Tests should be executed on stagenet with node version 6.0.1 and protocol version 6.
- Tests should be completed between 05-07 (when stagenet is expected to be ready in the newest versions) and 31-07 (when stagenet is reset).
- As usual, please get all the details from @abizjak.

**Comment by DOBEN** [comment]
close as completed:
- The `publicKeyOf` and `check_account_signature` invokes were tested on stagenet with a basic wallet (one public key)
- More complex accounts (with several public keys/credentials) were tested on `integration_testing_library`.
