### ISSUE TITLE
Write timeout increase and decrease events to a log on DEBUG level

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-node#975]
Currently, timeout  events are logged on TRACE level. It would be useful to log timeout increase and decrease events on the DEBUG level as they occur.

This would make analysis a bit easier.

**Node version**
6.0.2

**Comment by td202** [comment]
Based on discussion, we will keep the timeout reset messages as TRACE level, but add DEBUG level messages whenever the round is advanced, indicating whether it is due to a timeout or a quorum certificate.
