### ISSUE TITLE
New Consensus Database Changes: address review comments

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-node#984]
This issue is to address review comments on the database changes from @chportma:

1. I cannot make sense of the comment on line 135 of `LowLevel.hs`, namely “The parent block is the (previous) highest certified block.” As far as I can tell, all certified blocks are added, regardless of whether their parent was the previous highest certified block or not. Furthermore, I do not see what “database invariant” (line 132) is related to the comment on line 135.
2. I think that the condition `cbEpoch highCB <= 2 + tcMinEpoch lastTimeout` on line 329 of `StartUp.hs` will always be satisfied: suppose that cbEpoch highCB > 2 + tcMinEpoch lastTimeout, then the epoch of the LFB > 1 + tcMinEpoch lastTimeout (since the difference between the epochs of the highest CB and the LFB can be at most one), so the epoch of the LFB > tcMaxEpoch lastTimeout, hence the timeout points past the LFB, which is not possible for a valid timeout with `tcRound lastTimeout >= curRound`  (line 324). Maybe this test is there to check for some inconsistent in the stored data, but I don’t see why this test would be relevant. In any case, due to point 3 below, this might be removed altogether.
3. In line 335 of `StartUp.hs` a TC is being paired with the current highest CB, but the epoch might not be the one used to sum up the weights of the signatures in the TC. We have stored all CBs, so in particular we will have stored the one that was the highest CB when this TC was generated, but I don’t see any way to find it without more information. Changing the type of the `prsLatestTimeout` to be `RoundTimeout` should be (more than) enough I think.
4. Near the end of `loadCertifiedBlocks` (no screenshot attached), we are adding `prsLastSignedTimeoutMessage` to `currentTimeoutMessages`. But we aren’t adding `prsLastSignedQuorumMessage` to `currentQuorumMessages`. Is there any reason for that? I don’t think that this is an issue, I just don’t see any reasons for adding the tm, but not the qm.

**Comment by abizjak** [comment]
As we discussed in the standup today, since this is not critical enough and unlikely to be a problem, we'll include it in the 6.1 release instead of 6.0.*.

**Comment by td202** [comment]
Resolution is as follows:

1. The condition in the comment is not needed, so is removed.
2. The test is redundant, but is kept to make it clear that the invariants of `RoundTimeout` are established.
3. Instead of simply pairing the timeout certificate with the highest certified block, we check if we might need to pair it with a different block, which will be one from another epoch, and if so determine the appropriate block to pair it with.
4. If the last signed quorum message is for an already-certified block, then we don't need to add it to the quorum messages. If it is for a non-certified block, then we will no longer have that block, and so we should also not add it to the quorum messages.
