### ISSUE TITLE
GRPC changes: Documentation

### ISSUE THREAD

**Issue by MilkywayPirate** [Concordium/concordium-node#987]
For release 6.1.x new commands exposed in the high level API of the concordium client must be described in our developer documentation.

The raw  API itself should also have it documentation rebuilt after release.

**Comment by abizjak** [comment]
The raw commands are not really covered in developer documentation. I don't think we need to start that.

We have the generated (and linked to from developer documentation) GRPC documentation which should document these APIs.

The new high-level commands should be described in the relevant developer documentation section though.

**Comment by EmilLa1** [comment]
> The raw commands are not really covered in developer documentation. I don't think we need to start that.
> 
> We have the generated (and linked to from developer documentation) GRPC documentation which should document these APIs.
> 
> The new high-level commands should be described in the relevant developer documentation section though.

Changed description of task.

**Comment by abizjak** [comment]
Is this still relevant, does something need to be done, or should this be closed?

**Comment by dg-concordium** [comment]
I think this was done, wasn't it?

**Comment by EmilLa1** [comment]
This pr https://github.com/Concordium/concordium.github.io/pull/912 solves this issue.
