### ISSUE TITLE
InvokeInstance incorrectly counts the amount as the payment amount.

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-node#998]
**Bug Description**

When running InvokeInstance, the amount that is supplied is used both as the amount to transfer to the instance, and the amount that is reserved for payment of fees. This latter part is incorrect and can lead to spurious "insufficient funds" errors when dry-running contract updates.

**Steps to Reproduce**

```
./concordium-client --grpc-ip node.tesntet.concordium.com contract invoke 5881 --entrypoint receive --invoker-account $ACCOUNT --amount ...
```
works when the amount ... is <= 1/2 of the accounts amount but not if it is more.

The contract being invoked is simple
```
#[receive(contract = "test_invoke_instance", name = "receive", mutable, payable)]
fn receive<S: HasStateApi>(
    _ctx: &impl HasReceiveContext,
    _host: &mut impl HasHost<State, StateApiType = S>,
    _amount: Amount,
) -> ReceiveResult<()> {
    Ok(())
}
```

**Versions**
- Software Version: <= 6.0.4

**Comment by mh-concordium** [comment]
Just for information, now there is the same contract (index 5) initialized on Stagenet if needed for testing.
